api-version: '1.21'

# Change all of these to your plugin's information
name: FFA
load: POSTWORLD
version: '0.1.0'
main: de.dasphiller.ffa.FFA
description: FFA
authors: [ xPhiller ]
libraries:
  - net.axay:kspigot:1.21